OPENAI_API_KEY = "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"
OPENAI_ORG_ID = "org-gUZda0ychHf6LOX0PL9WzOPu"
OPENAI_PROJECT_ID = "proj_OnCx3c2ntfBnW6i1RVQh8pF1"
